### ISSUE TITLE
Issue Running MOP2

### ISSUE THREAD

**Issue by anaesco** [biocorecrg/MOP2#10]
Hi there, I have followed your steps to run MOP but I cannot seem to have any success. Could you help me out by letting me know if there are any errors in my configurations at the Preprocess step?

N E X T F L O W  ~  version 21.04.3
Launching `mop_preprocess.nf` [determined_carson] - revision: ecf5447b25

╔╦╗╔═╗╔═╗  ╔═╗┬─┐┌─┐┌─┐┬─┐┌─┐┌─┐┌─┐┌─┐┌─┐
║║║║ ║╠═╝  ╠═╝├┬┘├┤ ├─┘├┬┘│ ││  ├┤ └─┐└─┐
╩ ╩╚═╝╩    ╩  ┴└─└─┘┴  ┴└─└─┘└─┘└─┘└─┘└─┘

====================================================
BIOCORE@CRG Master of Pores 2. Preprocessing - N F  ~  version 2.0
====================================================

conffile                                  : final_summary_01.txt

fast5                     : /home/cart/EpiTX/master_of_pores/NanoPreprocess/data/41147_pellet/pellet/*.fast5
fastq                       :

reference                    : /home/cart/EpiTX/MOP2/Reference                                                                                                 /GRCh38.primary_assembly.genome.fa.gz
annotation                : /home/cart/EpiTX/MOP2/Reference/gencode.v39.annotation.gtf.gz

granularity                               : 1

ref_type                                    : genome
pars_tools                                : drna_tool_splice_opt.tsv

output                                      :

GPU                                        : OFF

basecalling                          : guppy
demultiplexing                     : guppy
demulti_fast5                 : NO

filtering                            : nanofilt
mapping                          : graphmap2

counting                         : nanocount
discovery                         : NO

cram_conv                        : YES
subsampling_cram              : 50

saveSpace                     : NO

email                     : 

----------------------CHECK TOOLS -----------------------------
basecalling : guppy
demultiplexing : guppy
mapping : graphmap2
filtering : nanofilt
counting : nanocount
> discovery will be skipped
--------------------------------------------------------------
[-        ] process > flow2:GUPPY_BASECALL_DEMULTI:baseCallAndDemultiPlex -
[-        ] process > flow2:NANOFILT_FILTER:filter                        -
[-        ] process > preprocess_flow:MinIONQC                            -
[-        ] process > preprocess_flow:GRAPHMAP2:map                       -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln                 -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln               -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam             -
[-        ] process > preprocess_flow:checkRef

**Comment by lucacozzuto** [comment]
Hi, which is the command line you are using? In which infrastructure are you running it?

**Comment by lucacozzuto** [comment]
is just one machine?? You have to add -profile local

**Comment by lucacozzuto** [comment]
yes it is

**Comment by lucacozzuto** [comment]
this is strange... it should take some time to pull down the docker images and then execute. Can you check if your docker is up and running?

**Comment by anaesco** [comment]
Ok just checked and it is up and running.

**Comment by lucacozzuto** [comment]
Can you try the test dataset?  Just for checking that the pipeline is ok

**Comment by anaesco** [comment]
Sure, I found the fast5 file and the reference, but cannot localize the annotation file. Should I just try it without?

**Comment by lucacozzuto** [comment]
Yes the params is here:
https://github.com/biocorecrg/MOP2/blob/main/mop_preprocess/params.config.test

**Comment by anaesco** [comment]
Ok found the error!  it seems to be an issue with guppy basecalling, any help to fix it is super appreciated!!!

Error executing process > 'flow1:GUPPY_BASECALL:baseCall (mod---2)'

Caused by:
  Process `flow1:GUPPY_BASECALL:baseCall (mod---2)` terminated with an error exit status (127)

Command executed:

  guppy_basecaller          --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002  -i ./         --save_path ./mod---2_out         --gp>
  cat mod---2_out/*.fastq >> mod---2.fastq
  rm mod---2_out/*.fastq
  gzip mod---2.fastq

Command exit status:
  127

Command output:
  (empty)

**Comment by lucacozzuto** [comment]
did you installed guppy using bash INSTALL.sh ?

**Comment by anaesco** [comment]
This computer was used to run MOP1, so I assumed yes; however, the command guppy_basecaller --print_workflows cannot be found... I'm gonna go ahead and install it ha

**Comment by anaesco** [comment]
hi me again! so I installed guppy and restarted the terminal, but still no success
command line used: nextflow run mop_preprocess.nf -profile local -with-docker > log.txt

----------------------CHECK TOOLS -----------------------------
basecalling : guppy
> demultiplexing will be skipped
mapping : graphmap
filtering : nanoq
counting : nanocount
> discovery will be skipped
--------------------------------------------------------------
[-        ] process > flow1:GUPPY_BASECALL:baseCall            -
[-        ] process > flow1:NANOQ_FILTER:filter                -
[-        ] process > preprocess_flow:MinIONQC                 -
[-        ] process > preprocess_flow:RNA2DNA                  -
[-        ] process > preprocess_flow:GRAPHMAP:map             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam  -
[-        ] process > preprocess_flow:checkRef                 -
[-        ] process > preprocess_flow:bam2Cram                 -
[-        ] process > preprocess_flow:bam2stats                -
[-        ] process > preprocess_flow:joinAlnStats             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot -
[-        ] process > preprocess_flow:concatenateFastQFiles    -
[-        ] process > preprocess_flow:FASTQC:fastQC            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount      -
[-        ] process > preprocess_flow:AssignReads              -
[-        ] process > preprocess_flow:countStats               -
[-        ] process > preprocess_flow:joinCountStats           -
[-        ] process > preprocess_flow:MULTIQC:makeReport       -

executor >  local (3)
[2e/62d1cc] process > flow1:GUPPY_BASECALL:baseCall (wt---1)                   [  0%] 0 of 2
[-        ] process > flow1:NANOQ_FILTER:filter                                -
[-        ] process > preprocess_flow:MinIONQC                                 -
[-        ] process > preprocess_flow:RNA2DNA                                  -
[-        ] process > preprocess_flow:GRAPHMAP:map                             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln                      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln                    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam                  -
[4b/c63495] process > preprocess_flow:checkRef (Checking yeast_rRNA_ref.fa.gz) [  0%] 0 of 1
[-        ] process > preprocess_flow:bam2Cram                                 -
[-        ] process > preprocess_flow:bam2stats                                -
[-        ] process > preprocess_flow:joinAlnStats                             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot                 -
[-        ] process > preprocess_flow:concatenateFastQFiles                    -
[-        ] process > preprocess_flow:FASTQC:fastQC                            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount                      -
[-        ] process > preprocess_flow:AssignReads                              -
[-        ] process > preprocess_flow:countStats                               -
[-        ] process > preprocess_flow:joinCountStats                           -
[-        ] process > preprocess_flow:MULTIQC:makeReport                       -

executor >  local (3)
[2e/62d1cc] process > flow1:GUPPY_BASECALL:baseCall (wt---1)                   [  0%] 0 of 2
[-        ] process > flow1:NANOQ_FILTER:filter                                -
[-        ] process > preprocess_flow:MinIONQC                                 -
[-        ] process > preprocess_flow:RNA2DNA                                  -
[-        ] process > preprocess_flow:GRAPHMAP:map                             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln                      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln                    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam                  -
[4b/c63495] process > preprocess_flow:checkRef (Checking yeast_rRNA_ref.fa.gz) [  0%] 0 of 1
[-        ] process > preprocess_flow:bam2Cram                                 -
[-        ] process > preprocess_flow:bam2stats                                -
[-        ] process > preprocess_flow:joinAlnStats                             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot                 -
[-        ] process > preprocess_flow:concatenateFastQFiles                    -
[-        ] process > preprocess_flow:FASTQC:fastQC                            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount                      -
[-        ] process > preprocess_flow:AssignReads                              -
[-        ] process > preprocess_flow:countStats                               -
[-        ] process > preprocess_flow:joinCountStats                           -
[-        ] process > preprocess_flow:MULTIQC:makeReport                       -
Error executing process > 'flow1:GUPPY_BASECALL:baseCall (mod---2)'

Caused by:
  Process `flow1:GUPPY_BASECALL:baseCall (mod---2)` terminated with an error exit status (127)

Command executed:

  guppy_basecaller          --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002  -i ./         --save_path ./mod---2_out         --gpu_runners_per_device 1         --cpu_thr>
  cat mod---2_out/*.fastq >> mod---2.fastq
  rm mod---2_out/*.fastq
  gzip mod---2.fastq

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: guppy_basecaller: command not found


Work dir:
  /home/carter-balaj/EpiTX/MOP2/mop_preprocess/work/54/00f01b83860b3150ac85ecfe5fa491

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line


Pipeline BIOCORE@CRG Master of Pore - preprocess completed!
Started at  2022-03-15T13:20:06.030172-04:00
Finished at 2022-03-15T13:20:14.513135-04:00
Time elapsed: 8.5s
Execution status: failed
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_preprocess.nf' at line: 631 or see '.nextflow.log' file for more details

**Comment by anaesco** [comment]
Oh lord! I finally got it to run!! thanks for your help so much.

Started at  2022-03-15T13:58:29.891882-04:00
Finished at 2022-03-15T14:14:12.908871-04:00
Time elapsed: 15m 43s
Execution status: OK
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_preprocess.nf' at line: 631 or see '.nextflow.log' file for more details
Completed at: 15-Mar-2022 14:14:12
Duration    : 15m 43s
CPU hours   : 0.5
Succeeded   : 36


But lastly!!! **Should I ** be concerned about the "Failed to invoke 'workflow...' result?
