### ISSUE TITLE
singularity pull / credentials for quay.io

### ISSUE THREAD

**Issue by trum994** [biocorecrg/MOP2#11]
```
Error executing process > 'flow1:NANOQ_FILTER:filter (wt---1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name quay.io-biocontainers-nanoq-0.8.2--h779adbc_0.img.pulling.1647379514424 docker://quay.io/biocontainers/nanoq:0.8.2--h779adbc_0 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://quay.io/biocontainers/nanoq:0.8.2--h779adbc_0: unable to retrieve auth token: invalid username/password: unauthorized: Invalid Username or Password
```

Upon seeing this error I got user/pass from quay.io. I can now manually build these images. But when I run nextflow:
`nextflow run mop_preprocess.nf -with-singularity -bg -profile slurm
`
 I see the same authentication error again. How do I pass my quay.io credentials to nextflow for creating singularity images?

**Comment by lucacozzuto** [comment]
Sorry, but you don't need any password for pulling from quay.io, at least until now... I use some biocontainers images so this is the reason we are pulling the images from there.
