### ISSUE TITLE
Starting MoP2 from MoP_TAIL

### ISSUE THREAD

**Issue by Wardale24** [biocorecrg/MOP2#12]
Hello!

We would like to know if there is any chance we can begin using MoP2 from the MoP_TAIL section. It has been made clear that the input for MoP_TAIL is the output from MoP_PREPROCESS, but we have already basecalled our fast5 files, checked qc and mapped to transcriptome using minimap2. 

Given the lengthy time and memory consumption it would take to repeat this step in MoP_PREPROCESS for 6 datasets, we would like to begin from MoP_TAIL. Could there be any issues that may arise from this? Is there a process you would recommend carrying out before we do this? And if you would be so kind, could you share what the output folders of MoP_PREPROCESS would look like so we can simulate this with our already-achieved results to "disguise" it as output from MoP_PREPROCESS?

Thank you so much in advance!

Alex

**Comment by lucacozzuto** [comment]
Hi, thanks for using our tool. You can run mop_tail on your data, you just need to "reproduce" the output structure from mop_prerpocess. In particular, you need:
 
- Bam and bai files in alignment folder
- fq.gz files in fastq_files folder
- different folders into fast5_files containing fast5 files
- *.assigned files into assigned folder with a correspondence READ<tab>TRANSCRIPT_ID

You might want to check here for an example of the output folder structure:

https://github.com/biocorecrg/MOP2/tree/test_results/output_pre
 
Best,

Luca

**Comment by Wardale24** [comment]
This is perfect, thank you Luca!
