### ISSUE TITLE
mop_mod.nf failed execution

### ISSUE THREAD

**Issue by anaesco** [biocorecrg/MOP2#13]
Hi there, I ran the command: nextflow run mop_mod.nf -with-docker > log.txt

But after 6 hours, the execution failed and it also let me know about an error. I'm unsure how to fix this, so I'd appreciate any help! I am currently using the test data parameters.

(...)
executor >  local (3)
[0d/41ca87] process > checkRef (Checking yeast_rRNA_ref.fa.gz)              [100%] 1 of 1, cached: 1 ✔
[0f/fb5c06] process > epinano_flow:splitReference (Splitting of referenc... [100%] 1 of 1, cached: 1 ✔
[e5/ab50d7] process > epinano_flow:splitBams (Splitting of ko_2_s.bam on... [100%] 6 of 6, cached: 6 ✔
[25/2625ab] process > epinano_flow:indexReference (Indexing pieces00.fa)    [100%] 1 of 1, cached: 1 ✔
[e3/d89938] process > epinano_flow:EPINANO_CALC_VAR_FREQUENCIES (wt_2___... [ 33%] 2 of 6, cached: 2
[-        ] process > epinano_flow:joinEpinanoRes                           -
[-        ] process > epinano_flow:makeEpinanoPlots_ins                     -
[-        ] process > epinano_flow:makeEpinanoPlots_mis                     -
[-        ] process > epinano_flow:makeEpinanoPlots_del                     -
[c6/ae2355] process > tombo_common_flow:multiToSingleFast5 (mod___batch_0)  [100%] 2 of 2, cached: 2 ✔
[f0/efdd51] process > tombo_common_flow:TOMBO_RESQUIGGLE_RNA:resquiggle_... [100%] 2 of 2, cached: 2 ✔
[c0/aa1c0f] process > getChromInfo (reference.fa)                           [100%] 1 of 1, cached: 1 ✔
[-        ] process > tombo_msc_flow:TOMBO_GET_MODIFICATION_MSC:getModif... [  0%] 0 of 1
[-        ] process > bedGraphToWig_msc                                     -
[-        ] process > tombo_lsc_flow:TOMBO_GET_MODIFICATION_LSC:getModif... [  0%] 0 of 1
[-        ] process > bedGraphToWig_lsc                                     -
[-        ] process > wigToBigWig                                           -
[-        ] process > mergeTomboWigsPlus                                    -
[-        ] process > mergeTomboWigsMinus                                   -
[f9/967581] process > EPINANO_VER:getVersion                                [100%] 1 of 1, cached: 1 ✔
[8f/b21e5f] process > NANOPOLISH_VER:getVersion                             [100%] 1 of 1, cached: 1 ✔
[8f/8b5c64] process > NANOCOMPORE_VER:getVersion                            [100%] 1 of 1, cached: 1 ✔
[db/f570b6] process > TOMBO_VER:getVersion                                  [100%] 1 of 1, cached: 1 ✔
Error executing process > 'epinano_flow:EPINANO_CALC_VAR_FREQUENCIES (wt_1___pieces00_s.bam on wt_1)'

Caused by:
  Process exceeded running time limit (6h)

Command executed:

  Epinano_Variants.py -n 8 -R pieces00.fa -b wt_1___pieces00_s.bam -s $SAM2TSV --type t
  for i in *.csv; do gzip $i; done

Command exit status:
  -

Command output:
  (empty)

Command error:
  wt_1___pieces00_s_TMP_ already exists, will overwrite it
  Process Process-2:
  Traceback (most recent call last):
    File "/usr/local/python/versions/3.6.3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
      self.run()
    File "/usr/local/python/versions/3.6.3/lib/python3.6/multiprocessing/process.py", line 93, in run
      self._target(*self._args, **self._kwargs)
    File "/project/Epinano1.2.0/Epinano_Variants.py", line 45, in split_tsv_for_per_site_var_freq
      firstline = next (tsv)

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.>

Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2022-03-15T17:28:37.791708-04:00
Finished at 2022-03-15T23:28:45.450440-04:00
Time elapsed: 6h 8s
Execution status: failed
WARN: Killing pending tasks (1)

**Comment by lucacozzuto** [comment]
I recall you are using a single computer. So, please add -profile local and then if you need to increase memory / etc you can manually change the file conf/local.config in which we specify the resources needed

**Comment by anaesco** [comment]
Hi there its been a while, but I finally got around to using the mop_mod again. this time I am getting different results. 

[comparison03_31_22.txt](https://github.com/biocorecrg/MOP2/files/8392260/comparison03_31_22.txt)

Once I check the script on line 112, 
I see this: 
/*
 * Creates the channels with comparisons
 */

compfile = file(params.comparison)
if( !compfile.exists() ) exit 1, "Missing comparison file: ${compfile}. Specify path with --comparisons"

 Channel
    .from(compfile.readLines())
    .map { line ->
        list = line.split("\t")
        if (list[0]!= "") {
            def sampleID = list[0]
            def ctrlID = list[1]
            [ sampleID, ctrlID ]
        }
    }.set {comparisons}



i am not able to localize the params.comparison file. how can I fix this error?

**Comment by anaesco** [comment]
Hi there, turns out we were setting the comparison file incorrectly, I have rerun this mod with no errors as of now! Thanks!!
