### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by rmoran7** [biocorecrg/MOP2#19]
Hi, 

Running install as per docs and the first test on an EC2  instance , but with docker and i get an issue:

`docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /project/minimap2-2.17_x64-linux: invalid argument
`
I am not sure what the issue is ?

**Comment by rmoran7** [comment]
My input command is like this: 
nextflow run mop_preprocess.nf -with-docker  -profile local : 
Unable to find image 'biocorecrg/mopprepr:0.7' locally
0.7: Pulling from biocorecrg/mopprepr 
....
i get the above error after like 2 mins.

**Comment by toniher** [comment]
Hi @rmoran7, are you deploying the EC2 instance using our provided Terraform scripts?

**Comment by toniher** [comment]
So far, we could only support you if using our Terraform recipes, but for sake of reference, the image we use is defined here:
https://github.com/biocorecrg/MOP2/blob/main/terraform/awsbatch/config.sh
You might need to copy it from eu-central-1 region to yours...
