### ISSUE TITLE
Issues with install/testing?

### ISSUE THREAD

**Issue by FrancescoGarassino** [biocorecrg/MOP2#2]
Hi,

Thank you so much for making this interesting tool available! Today I followed the documentation on how to install and everything seemed to go well. When I tried running the command you report under 'Testing', I got something weird.

command:

`nextflow run mop_preprocess.nf -with-singularity -bg -profile local > log`

contents of log file:

```
N E X T F L O W  ~  version 18.10.1
Launching `mop_preprocess.nf` [desperate_church] - revision: ecf5447b25
ERROR ~ unable to resolve class GUPPY_BASECALL
 @ line 152, column 26.
   include { GET_WORKFLOWS; BASECALL as GUPPY_BASECALL; BASECALL_DEMULTI as GUPPY_BASECALL_DEMULTI } from "${subworkflowsDir}/basecalling/guppy" addParams(EXTRAPARS_BC: guppy_basecall_pars, EXTRAPARS_DEM: progPars["demultiplexing--guppy"], LABEL: guppy_basecall_label, GPU_OPTION: gpu, MOP: "YES", OUTPUT: output_bc, OUTPUTMODE: outmode)
                            ^

_nf_script_3f0a42d3: 152: unable to resolve class GUPPY_BASECALL_DEMULTI
 @ line 152, column 54.
   ; BASECALL as GUPPY_BASECALL; BASECALL_D
                                 ^

_nf_script_3f0a42d3: 153: unable to resolve class DEMULTIPLEX_VER
 @ line 153, column 11.
   include { GET_VERSION as DEMULTIPLEX_VER; DEMULTIPLEX as DEMULTIPLEX_DEEPLEXICON } from "${subworkflowsDir}/demultiplexing/deeplexicon" addParams(EXTRAPARS: progPars["demultiplexing--deeplexicon"], LABEL:deeplexi_basecall_label, GPU_OPTION: gpu)
             ^
```

..and it keeps going and reports a total of 37 similar errors. I'll attach the whole log file.

[log.txt](https://github.com/biocorecrg/MOP2/files/7953268/log.txt)

What's not going well? Is it me (I have zero nextflow experience)?

Thanks,

Francesco

**Comment by lucacozzuto** [comment]
Hi,

It looks like your Nextflow is quite outdated... Try to update it to the
latest version.

Luca

Il gio 27 gen 2022, 20:31 Francesco Garassino ***@***.***> ha
scritto:

**Comment by lucacozzuto** [comment]
Hi, any news about this?

**Comment by FrancescoGarassino** [comment]
Hi Luca,

I did indeed need to update Nextflow! That allowed the pipeline to run, though now I'm getting some error with Guppy that I can't quite understand (sorry for my illiteracy here...). I'll attach the log file if you want to take a look.

Cheers,

Francesco

[log_1.txt](https://github.com/biocorecrg/MOP2/files/7970010/log_1.txt)

**Comment by lucacozzuto** [comment]
Hi, it looks like a singularity error. Which version are you using?

**Comment by FrancescoGarassino** [comment]
Hi, I have 3.8.5 (installed via conda)

**Comment by lucacozzuto** [comment]
I have the version 3.2.1... but 3.8.5 should also work. Likely there is some configuration issue, I see that this:

```
Command error:
  INFO:    Converting SIF file to temporary sandbox...
  INFO:    Cleaning up image...
  FATAL:   container creation failed: failed to add  as session directory: path . is not an absolute path
```

maybe you should  give an absolute path somewhere. Try to google it or to use another version. I never heard about this problem, sorry

**Comment by FrancescoGarassino** [comment]
No worries, I'll try some things and let you know!

**Comment by FrancescoGarassino** [comment]
Hi Luca,

So it seems my issues were due to the fact I installed singularity via conda. I am now running the pipeline with a non-conda singularity and fixed this error. Dealing with some other things atm (issues with pulling images if I understood correctly) but it seems our bioinformaticians can sort through them!

Thanks a lot for all the help!

Francesco

**Comment by lucacozzuto** [comment]
You are welcome! If you need any help or your bioinfo wants to contribute/improve something, let us know.

Best,
Luca
