### ISSUE TITLE
Run mop_preprocess with Apple M1 chip

### ISSUE THREAD

**Issue by chusopascual** [biocorecrg/MOP2#22]
Hi,

I am running the mop_preprocess workflow in a computer with an Apple M1 chip. I am getting an error related to it. Is there any way to circumvent it? The workflow is completed successfully when I include just a couple of input file, but it crashes when I include the entire set of files I need to analyze.

Thanks!
Jesús.

N E X T F L O W  ~  version 22.04.0
Launching `mop_preprocess.nf` [sad_majorana] DSL2 - revision: ec40fe0af4

╔╦╗╔═╗╔═╗  ╔═╗┬─┐┌─┐┌─┐┬─┐┌─┐┌─┐┌─┐┌─┐┌─┐
║║║║ ║╠═╝  ╠═╝├┬┘├┤ ├─┘├┬┘│ ││  ├┤ └─┐└─┐
╩ ╩╚═╝╩    ╩  ┴└─└─┘┴  ┴└─└─┘└─┘└─┘└─┘└─┘
                                                                                       
====================================================
BIOCORE@CRG Master of Pores 2. Preprocessing - N F  ~  version 2.0
====================================================

conffile.                 : /Users/j/MOP2/data/W/final_summary_FAR92050_1b93b532.txt

fast5                     : 
fastq                     : /Users/j/MOP2/data/W/fastq_pass/*.fastq.gz

reference                 : /Users/j/MOP2/anno/At.fa
annotation                : 

granularity.              : 5

ref_type                  : transcriptome
pars_tools                : drna_tool_splice_opt.tsv

output                    : /Users/j/MOP2/output/

GPU                       : ON

basecalling               : NO 
demultiplexing            : NO 
demulti_fast5             : NO

filtering                 : nanoq
mapping                   : minimap2

counting                  : nanocount
discovery                 : bambu

cram_conv           	  : NO
subsampling_cram          : NO

saveSpace                 : NO
email                     : 

Skipping the email

----------------------CHECK TOOLS -----------------------------
> basecalling will be skipped
> demultiplexing will be skipped
mapping : minimap2
filtering : nanoq
counting : nanocount
discovery : bambu
--------------------------------------------------------------
[-        ] process > preprocess_simple:FASTQC:fa... -

[-        ] process > preprocess_simple:FASTQC:fa... -
[-        ] process > preprocess_simple:MINIMAP2:map -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

[-        ] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 20
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 10
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (2)
[f5/7a6bac] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 41
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 36
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (9)
[d9/74fd83] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 60
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 53
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 72
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 64
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 86
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 81
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 118
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 104
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 178
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 168
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 185
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 175
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 198
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 186
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 208
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 196
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 210
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 201
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 231
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 218
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 252
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 233
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 270
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 259
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 296
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 283
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (10)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 323
[-        ] process > preprocess_simple:MINIMAP2:map [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (11)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  0%] 0 of 323
[fd/bc4a52] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (12)
[7f/54b157] process > preprocess_simple:FASTQC:fa... [  0%] 2 of 323
[44/96cc2e] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (12)
[7f/54b157] process > preprocess_simple:FASTQC:fa... [  0%] 2 of 323
[44/96cc2e] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (13)
[f2/0e9713] process > preprocess_simple:FASTQC:fa... [  0%] 3 of 323
[a6/dc7f07] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (14)
[bf/fb552b] process > preprocess_simple:FASTQC:fa... [  1%] 4 of 323
[80/aae8d2] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (15)
[7b/80748a] process > preprocess_simple:FASTQC:fa... [  1%] 5 of 323
[df/14a7ec] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (16)
[f5/7a6bac] process > preprocess_simple:FASTQC:fa... [  1%] 6 of 323
[98/1e7dce] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (17)
[f6/65194f] process > preprocess_simple:FASTQC:fa... [  2%] 7 of 323
[f9/242a42] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (19)
[20/952b18] process > preprocess_simple:FASTQC:fa... [  2%] 9 of 323
[8f/41e61d] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (20)
[b2/64f673] process > preprocess_simple:FASTQC:fa... [  3%] 10 of 323
[bb/6366af] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -

executor >  local (21)
[cf/17126d] process > preprocess_simple:FASTQC:fa... [  3%] 10 of 323
[bb/6366af] process > preprocess_simple:MINIMAP2:... [  0%] 0 of 323
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -
Error executing process > 'preprocess_simple:MINIMAP2:map (FAR92050_pass_1b93b532_287)'

Caused by:
  Process `preprocess_simple:MINIMAP2:map (FAR92050_pass_1b93b532_287)` terminated with an error exit status (1)

Command executed:

  minimap2 -t 1 -a -uf -ax splice -k14 At.fa FAR92050_pass_1b93b532_287.fastq.gz | samtools view -@ 1 -F4 -hSb - > FAR92050_pass_1b93b532_287.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  [M::mm_idx_gen::29.912*0.65] collected minimizers
  [main_samview] fail to read the header from "-".

Work dir:
  /Users/j/MOP2/mop_preprocess/work/98/1e7dceeb1693b263391ae6cd69f897

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

Pipeline BIOCORE@CRG Master of Pore - preprocess completed!
Started at  2022-06-01T12:32:24.699108+02:00
Finished at 2022-06-01T12:34:35.078982+02:00
Time elapsed: 2m 10s
Execution status: failed
WARN: Killing running tasks (9)

executor >  local (21)
[cf/17126d] process > preprocess_simple:FASTQC:fa... [  3%] 10 of 323
[bb/6366af] process > preprocess_simple:MINIMAP2:... [  1%] 4 of 322, failed: 4
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:SAMTOOLS_... -
[-        ] process > preprocess_simple:bam2stats    -
[-        ] process > preprocess_simple:joinAlnStats -
[-        ] process > preprocess_simple:NANOPLOT_... -
[-        ] process > preprocess_simple:NANOCOUNT... -
[-        ] process > preprocess_simple:AssignReads  -
[-        ] process > preprocess_simple:countStats   -
[-        ] process > preprocess_simple:joinCount... -
[-        ] process > preprocess_simple:MULTIQC:m... -
Error executing process > 'preprocess_simple:MINIMAP2:map (FAR92050_pass_1b93b532_287)'

Caused by:
  Process `preprocess_simple:MINIMAP2:map (FAR92050_pass_1b93b532_287)` terminated with an error exit status (1)

Command executed:

  minimap2 -t 1 -a -uf -ax splice -k14 At.fa FAR92050_pass_1b93b532_287.fastq.gz | samtools view -@ 1 -F4 -hSb - > FAR92050_pass_1b93b532_287.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  [M::mm_idx_gen::29.912*0.65] collected minimizers
  [main_samview] fail to read the header from "-".

Work dir:
  /Users/jj/MOP2/mop_preprocess/work/98/1e7dceeb1693b263391ae6cd69f897

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by lucacozzuto** [comment]
Are you using docker? Here I found you can add an extra parameter:
https://stackoverflow.com/questions/66662820/m1-docker-preview-and-keycloak-images-platform-linux-amd64-does-not-match-th

```
--platform linux/amd64
```

You need to add it to the configuration file named local.config within local.config

```
    containerOptions = { workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g) --platform linux/amd64': null}
```

Let me know if it works for you

L

**Comment by chusopascual** [comment]
That solved the problem!

Thank you so much,
Jesús.

**Comment by Tako-liu** [comment]
Hi! I met the same problem. 
However, my operational system is Ubuntu. 
I use the solution you offer below, but it isn't work.
Any solution?
Thank you!

**Comment by lucacozzuto** [comment]
Hi, which error do you have? I fear this is out of the scope of this project to support multiple CPU architectures since the original tool embedded are not written for this CPUs

**Comment by Tako-liu** [comment]
Hi!
The error is the same as below :" [main_samview] fail to read the header from "-".
I don't understand the multiple CPU you said. Is that mean the pipeline don't  support multi CPU run? (to reach that I change local.config)
Thank you！
