### ISSUE TITLE
INSTALL.sh update links

### ISSUE THREAD

**Issue by gkanogiannis** [biocorecrg/MOP2#24]
When rerunning (to update guppy version for example) INSTALL.sh, it will fail when creating symlinks to ont-guppy bins and libs.

Maybe it could be updated to something like (to force symlinks)

```
ln -sf ont-guppy/bin/guppy_* .
ln -sf ont-guppy/lib/* .
```

Similar for the move operation 
`mv -f ont-guppy mop_preprocess/bin/`

**Comment by lucacozzuto** [comment]
nice thanks, this is indeed a good solution
