### ISSUE TITLE
conda singularity related error

### ISSUE THREAD

**Issue by JBerthelier** [biocorecrg/MOP2#25]
Dear MOP2 team, 

I am trying to prepocess the test data, 
however I got this issue related to guppy. 
I didnt found same error in other questions. Do you have an idea of the problem ?
I am running it on my local computer.

Thank you for the support.

N E X T F L O W  ~  version 22.04.5
Launching `mop_preprocess.nf` [special_ekeblad] DSL2 - revision: ec40fe0af4

╔╦╗╔═╗╔═╗  ╔═╗┬─┐┌─┐┌─┐┬─┐┌─┐┌─┐┌─┐┌─┐┌─┐
║║║║ ║╠═╝  ╠═╝├┬┘├┤ ├─┘├┬┘│ ││  ├┤ └─┐└─┐
╩ ╩╚═╝╩    ╩  ┴└─└─┘┴  ┴└─└─┘└─┘└─┘└─┘└─┘
                                                                                       
====================================================
BIOCORE@CRG Master of Pores 2. Preprocessing - N F  ~  version 2.0
====================================================

conffile.                 : final_summary_01.txt

fast5                     : /home/workplace/MoP2/MOP2/mop_preprocess/../data/**/*.fast5
fastq                     : 

reference                 : /home/workplace/MoP2/MOP2/mop_preprocess/../anno/yeast_rRNA_ref.fa.gz
annotation                : 

granularity.              : 1

ref_type                  : transcriptome
pars_tools                : drna_tool_splice_opt.tsv

output                    : /home/workplace/MoP2/MOP2/mop_preprocess/output

GPU                       : OFF

basecalling               : guppy 
demultiplexing            : NO 
demulti_fast5             : NO

filtering                 : nanoq
mapping                   : graphmap

counting                  : nanocount
discovery                 : NO

cram_conv           	  : YES
subsampling_cram          : 50

saveSpace                 : NO
email                     : j@oist.jp

Sending the email to j@oist.jp

----------------------CHECK TOOLS -----------------------------
basecalling : guppy
> demultiplexing will be skipped
mapping : graphmap
filtering : nanoq
counting : nanocount
> discovery will be skipped
--------------------------------------------------------------
[-        ] process > flow1:GUPPY_BASECALL:baseCall         -
[-        ] process > flow1:NANOQ_FILTER:filter             -
[-        ] process > preprocess_flow:MinIONQC              -
[-        ] process > preprocess_flow:RNA2DNA               -
[-        ] process > preprocess_flow:GRAPHMAP:map          -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln   -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln -

[-        ] process > flow1:GUPPY_BASECALL:baseCall            -
[-        ] process > flow1:NANOQ_FILTER:filter                -
[-        ] process > preprocess_flow:MinIONQC                 -
[-        ] process > preprocess_flow:RNA2DNA                  -
[-        ] process > preprocess_flow:GRAPHMAP:map             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam  -
[-        ] process > preprocess_flow:checkRef                 -
[-        ] process > preprocess_flow:bam2Cram                 -
[-        ] process > preprocess_flow:bam2stats                -
[-        ] process > preprocess_flow:joinAlnStats             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot -
[-        ] process > preprocess_flow:concatenateFastQFiles    -
[-        ] process > preprocess_flow:FASTQC:fastQC            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount      -
[-        ] process > preprocess_flow:AssignReads              -
[-        ] process > preprocess_flow:countStats               -
[-        ] process > preprocess_flow:joinCountStats           -
[-        ] process > preprocess_flow:MULTIQC:makeReport       -

[-        ] process > flow1:GUPPY_BASECALL:baseCall            [  0%] 0 of 2
[-        ] process > flow1:NANOQ_FILTER:filter                -
[-        ] process > preprocess_flow:MinIONQC                 -
[-        ] process > preprocess_flow:RNA2DNA                  -
[-        ] process > preprocess_flow:GRAPHMAP:map             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam  -
[-        ] process > preprocess_flow:checkRef                 -
[-        ] process > preprocess_flow:bam2Cram                 -
[-        ] process > preprocess_flow:bam2stats                -
[-        ] process > preprocess_flow:joinAlnStats             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot -
[-        ] process > preprocess_flow:concatenateFastQFiles    -
[-        ] process > preprocess_flow:FASTQC:fastQC            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount      -
[-        ] process > preprocess_flow:AssignReads              -
[-        ] process > preprocess_flow:countStats               -
[-        ] process > preprocess_flow:joinCountStats           -
[-        ] process > preprocess_flow:MULTIQC:makeReport       -
Pulling Singularity image docker://biocorecrg/mopprepr:0.7 [cache /home/workplace/MoP2/MOP2/mop_preprocess/../singularity/biocorecrg-mopprepr-0.7.img]

executor >  local (2)
[21/caa2f7] process > flow1:GUPPY_BASECALL:baseCall (mod---1)  [  0%] 0 of 2
[-        ] process > flow1:NANOQ_FILTER:filter                -
[-        ] process > preprocess_flow:MinIONQC                 -
[-        ] process > preprocess_flow:RNA2DNA                  -
[-        ] process > preprocess_flow:GRAPHMAP:map             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam  -
[-        ] process > preprocess_flow:checkRef                 -
[-        ] process > preprocess_flow:bam2Cram                 -
[-        ] process > preprocess_flow:bam2stats                -
[-        ] process > preprocess_flow:joinAlnStats             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot -
[-        ] process > preprocess_flow:concatenateFastQFiles    -
[-        ] process > preprocess_flow:FASTQC:fastQC            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount      -
[-        ] process > preprocess_flow:AssignReads              -
[-        ] process > preprocess_flow:countStats               -
[-        ] process > preprocess_flow:joinCountStats           -
[-        ] process > preprocess_flow:MULTIQC:makeReport       -
Pulling Singularity image docker://biocorecrg/mopprepr:0.7 [cache /home/workplace/MoP2/MOP2/mop_preprocess/../singularity/biocorecrg-mopprepr-0.7.img]
Error executing process > 'flow1:GUPPY_BASECALL:baseCall (wt---2)'

Caused by:
  Process `flow1:GUPPY_BASECALL:baseCall (wt---2)` terminated with an error exit status (255)

Command executed:

  guppy_basecaller          --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002  -i ./         --save_path ./wt---2_out         --gpu_runners_per_device 1         --cpu_threads_per_caller 1 	    --num_callers  1
  cat wt---2_out/*.fastq >> wt---2.fastq
  rm wt---2_out/*.fastq
  gzip wt---2.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR  : Session directory does not exist: /home/workplace/miniconda2/var/singularity/mnt/session
  ABORT  : Retval = 255
  

Work dir:
  /home/workplace/MoP2/MOP2/mop_preprocess/work/e6/2507fd3eb5346234484be1a085c723

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

Pipeline BIOCORE@CRG Master of Pore - preprocess completed!
Started at  2022-08-18T14:06:01.575654+09:00
Finished at 2022-08-18T14:06:19.136097+09:00
Time elapsed: 17.6s
Execution status: failed
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_preprocess.nf' at line: 632 or see '.nextflow.log' file for more details

executor >  local (2)
[21/caa2f7] process > flow1:GUPPY_BASECALL:baseCall (mod---1)  [100%] 2 of 2, failed: 2 ✘
[-        ] process > flow1:NANOQ_FILTER:filter                -
[-        ] process > preprocess_flow:MinIONQC                 -
[-        ] process > preprocess_flow:RNA2DNA                  -
[-        ] process > preprocess_flow:GRAPHMAP:map             -
[-        ] process > preprocess_flow:SAMTOOLS_CAT:catAln      -
[-        ] process > preprocess_flow:SAMTOOLS_SORT:sortAln    -
[-        ] process > preprocess_flow:SAMTOOLS_INDEX:indexBam  -
[-        ] process > preprocess_flow:checkRef                 -
[-        ] process > preprocess_flow:bam2Cram                 -
[-        ] process > preprocess_flow:bam2stats                -
[-        ] process > preprocess_flow:joinAlnStats             -
[-        ] process > preprocess_flow:NANOPLOT_QC:MOP_nanoPlot -
[-        ] process > preprocess_flow:concatenateFastQFiles    -
[-        ] process > preprocess_flow:FASTQC:fastQC            -
[-        ] process > preprocess_flow:NANOCOUNT:nanoCount      -
[-        ] process > preprocess_flow:AssignReads              -
[-        ] process > preprocess_flow:countStats               -
[-        ] process > preprocess_flow:joinCountStats           -
[-        ] process > preprocess_flow:MULTIQC:makeReport       -
Pulling Singularity image docker://biocorecrg/mopprepr:0.7 [cache /home/workplace/MoP2/MOP2/mop_preprocess/../singularity/biocorecrg-mopprepr-0.7.img]
Error executing process > 'flow1:GUPPY_BASECALL:baseCall (wt---2)'

Caused by:
  Process `flow1:GUPPY_BASECALL:baseCall (wt---2)` terminated with an error exit status (255)

Command executed:

  guppy_basecaller          --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002  -i ./         --save_path ./wt---2_out         --gpu_runners_per_device 1         --cpu_threads_per_caller 1 	    --num_callers  1
  cat wt---2_out/*.fastq >> wt---2.fastq
  rm wt---2_out/*.fastq
  gzip wt---2.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR  : Session directory does not exist: /home/workplace/miniconda2/var/singularity/mnt/session
  ABORT  : Retval = 255
  

Work dir:
  /home/workplace/MoP2/MOP2/mop_preprocess/work/e6/2507fd3eb5346234484be1a085c723

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by lucacozzuto** [comment]
Hi, can you send me your command line? Are you using docker or singularity? 
Best,

**Comment by JBerthelier** [comment]
Dear Luca, 

Thank you for the answer,
I am using the command: 

`` nextflow run mop_preprocess.nf -with-singularity -profile local``

I used FAST5 that are in "multi" format.
Best,

**Comment by lucacozzuto** [comment]
Hi,
From the error:

ERROR : Session directory does not exist: /home/workplace/miniconda2/var/singularity/mnt/session

It looks not a guppy problem but a problem of missing directory. Which operative system is? Can you revise the installation of singularity? Which version is? I don't have experience in installing singularity with miniconda, maybe it is not mounting the directory, I don't know.


Luca

**Comment by JBerthelier** [comment]
Dear Luca, 

Thank you very much for your help, 
Indeed, the error was caused by my singularity package in conda.
I did a regular singularity install and the Data test complete properly.
( I changed the name of the issue) 

I would like to ask you a question regarding memory and process setup.
MOP2 is running on a cluster, I would like to know the best way to increase the memory and number of cpu used.

Can I modify  "MOP2/conf/standard.config" to increasy those number ? and used the `--standard` option

Best regards

____________________________

process {
  cpus = 1
  memory='8G'
  cache='lenient'
  container = 'biocorecrg/mopprepr:0.7'
  containerOptions = { workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g)': null}

  withLabel: big_cpus {
		cpus = 8
		memory = '8G'
  }
  withLabel: big_cpus_ignore {
        errorStrategy = 'ignore'
        cpus = 8
        memory = '8G'
  } 
  withLabel: big_mem_cpus {
		time = '6h'
		cpus = 8
		memory = '30G'
  }
  withLabel: basecall_cpus {
		cpus = 8
		memory = '8G'
  }
  withLabel: basecall_gpus {
		maxForks = 1
		memory = '8G'
	containerOptions = { workflow.containerEngine == "singularity" ? '--nv':
		   ( workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g) --gpus all': null ) } 
  }
}

**Comment by lucacozzuto** [comment]
Nice! Which kind of scheduler are you using? You have slurm and SGE supported in conf folder. You can switch among them changing the -profile parameter.

Luca

**Comment by JBerthelier** [comment]
Dear Luca,

Many thanks for your help and your time, I am unsing slurm, I used you conf file.

For the module mop_tail,  I firsly got an error message related to "live basecalling" such as [here](https://github.com/adnaniazi/tailfindr/issues/10)
But after adding the option basecall_group = 'Basecall_1D_001' in the tools_opt.tsv (displayed below if someone else as the same issue), and now it works perfectly!
_________________________________________________________________
#flows      tool  extrapars
tailfindr   tailfindr   "basecall_group = 'Basecall_1D_001'"
nanopolish  nanopolish  ""
_________________________________________________________________

Also, I did a run with using SQK-RNA002 data, and 
sorry for my naive question, but now I will do a run with SQK-RNA001 data, 
can you confirm me that MOP2 reconize automaticaly the flowcell? Or should I add the --flowcell FLO-MIN106 --kit SQK-RNA002 info in the drna_splice_opt.tsv  ?

Thanks again for the support, I think this is my last question, you can next close this "issue windows"

Best

**Comment by lucacozzuto** [comment]
Hi, MOP2 recognize if you pass the config file produced by the sequencer (here an example: https://github.com/biocorecrg/MOP2/blob/main/mop_preprocess/final_summary_01.txt). If not you have to provide the guppy parameters or the model in the tools_opt.tsv file.  Single format means 1 read per fast5?

**Comment by JBerthelier** [comment]
Ok thanks for the info regarding the model/kit. I will change it. 
Yes for single format i mean 1 read per fast5.
Best

**Comment by lucacozzuto** [comment]
Hi, in theory, it should work. You can use the granularity parameter for grouping them together (let's say 4000) and use the guppy parameter --read_batch_size 4000 in the tools_opt.tsv file. From there you will have then a basecalled multi fast5 that can be used  for other pipelines
