### ISSUE TITLE
Error executing testing script

### ISSUE THREAD

**Issue by brooktila** [biocorecrg/MOP2#26]
Hi MOP2 team,

I wanted to use the MOP2 pipeline for RNA seq data and ran into some trouble at the testing stage. I hadn't made any changes to the installation file. But the [log](https://github.com/biocorecrg/MOP2/files/9569084/log.log) file says there is a script compilation error.

Here is my command line code:
(base) hp@MacBook-Pro-7 mop_preprocess % nextflow run mop_preprocess.nf -with-docker -bg -profile m1mac > log

Thank you!

**Comment by lucacozzuto** [comment]
Hi, I see your version of nextflow is quite old. I suggest you to use a newer one that fully support DSL2 (I'm using the version 22.04.5).

Best,

Luca

**Comment by brooktila** [comment]
Hi,

This seems to have solved the issue with the compile error. I just ran nextflow self-update
Thanks for the quick reply!

Regards,

Brook
