### ISSUE TITLE
Inverted results in polya_common/fast5_pass_joined.txt

### ISSUE THREAD

**Issue by YuancunZhao** [biocorecrg/MOP2#27]
Hi! Thank you for developing such a convenient workflow for ONT sequencing. But I encountered a small issue after running polyA module. It seems that Nanopolish and Tailfindr results were assigned to incorrect columns in jointed text. Maybe it was related to the incorrect parameter parsing order below?
https://github.com/biocorecrg/MOP2/blob/9469ca8ee92e68f593e6d8a7fb95a30d0e30e525/local_modules.nf#L698
I am not quite sure if this was my mistake. If the script was correct, please close this issue and sorry for bothering. 
Sincerely, Yuancun

**Comment by lucacozzuto** [comment]
Hi!
Good catch! I fixed it by changing mop_tail.nf 

https://github.com/biocorecrg/MOP2/commit/b20a643b0beef396916c4bc1bdcce32cecd6a307 

Luca
