### ISSUE TITLE
Preprocess with multiple Fast5 files?

### ISSUE THREAD

**Issue by jayradke** [biocorecrg/MOP2#29]
I have gotten the preprocess to work on single file using Docker. However, when I change the command to map to a folder that has multiple Fast5 files I get the following error...

Error executing process > 'flow1:GUPPY_BASECALL:baseCall (mop_preprocess---1)'

Caused by:
  Process `flow1:GUPPY_BASECALL:baseCall (mop_preprocess---1)` terminated with an error exit status (1)

Command executed:

  export LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs"
  guppy_basecaller -x "cuda:0"         --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002 --disable_qscore_filtering -i ./         --save_path ./mop_preprocess---1_out         --gpu_runners_per_device 1         --cpu_threads_per_caller 1           --num_callers  1
  cat mop_preprocess---1_out/*.fastq >> mop_preprocess---1.fastq
  rm mop_preprocess---1_out/*.fastq
  gzip mop_preprocess---1.fastq

Command exit status:
  1

Command output:
  CRASHPAD MESSAGE:
  ONT Guppy basecalling software version 6.3.7+532d626, minimap2 version 2.22-r1101

Do I need to use Singularity instead of Docker for this to work on the GPU with multiple files? Works on GPU with a single file with Docker.

Jay

**Comment by lucacozzuto** [comment]
Hi,

Can you pass me the parameters you used? And the whole error log? 

Luca

**Comment by jayradke** [comment]
Luca,

Here are the parameters..
conffile.                 : final_summary_01.txt

fast5                     : //mnt/h/test
fastq                     : 

reference                 : Genome.fa
annotation                : Annotation.gtf

granularity.              : 5

ref_type                  : genome
pars_tools                : drna_tool_unsplice_guppy6_opt.tsv

output                    : //mnt/h/Output

GPU                       : ON

basecalling               : guppy 
demultiplexing            : NO 
demulti_fast5             : NO

filtering                 : nanoq
mapping                   : minimap2

counting                  : NO
discovery                 : NO

cram_conv           	  : YES
subsampling_cram          : 50

**Comment by jayradke** [comment]
Sep-29 12:02:13.711 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'flow1:GUPPY_BASECALL:baseCall (h---1)'

Caused by:
  Process `flow1:GUPPY_BASECALL:baseCall (h---1)` terminated with an error exit status (1)

Command executed:

  export LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs"
  guppy_basecaller -x "cuda:0"         --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002 --disable_qscore_filtering -i ./         --save_path ./h---1_out         --gpu_runners_per_device 1         --cpu_threads_per_caller 1 	    --num_callers  1
  cat h---1_out/*.fastq >> h---1.fastq
  rm h---1_out/*.fastq
  gzip h---1.fastq

Command exit status:
  1

Command output:
  CRASHPAD MESSAGE: 
  ONT Guppy basecalling software version 6.3.7+532d626, minimap2 version 2.22-r1101
  config file:        /home/jayradke/MOP2/mop_preprocess/bin/ont-guppy/data/rna_r9.4.1_70bps_hac.cfg
  model file:         /home/jayradke/MOP2/mop_preprocess/bin/ont-guppy/data/template_rna_r9.4.1_70bps_hac.jsn
  input path:         ./
  save path:          ./h---1_out
  chunk size:         2000
  chunks per runner:  512
  records per file:   4000
  num basecallers:    1
  gpu device:         cuda:0
  kernel path:        
  runners per device: 1
  
  Use of this software is permitted solely under the terms of the end user license agreement (EULA).By running, copying or accessing this software, you are demonstrating your acceptance of the EULA.
  The EULA may be found in /home/jayradke/MOP2/mop_preprocess/bin/ont-guppy/bin
  Warning: fast5_out is deprecated - emitting fast5 files from guppy will be removed in a future version
  Found 0 input read files to process.
  Init time: 873 ms
  
  0%   10   20   30   40   50   60   70   80   90   100%
  |----|----|----|----|----|----|----|----|----|----|
  ***************************************************
  Caller time: 100 ms, Samples called: 0, samples/s: 0
  Finishing up any open output files.
  Basecalling completed successfully.

Command error:
  cat: 'h---1_out/*.fastq': No such file or directory

Work dir:
  /mnt/h/Work/38/be75261b355140af7b1ca54eadb3ae

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Sep-29 12:02:13.718 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `flow1:GUPPY_BASECALL:baseCall (h---1)` terminated with an error exit status (1)
Sep-29 12:02:13.741 [Task monitor] DEBUG nextflow.Session - The following nodes are still active:
[process] preprocess_flow:MULTIQC:makeReport
  status=ACTIVE
  port 0: (value) bound ; channel: input
  port 1: (cntrl) -     ; channel: $

Sep-29 12:02:13.746 [main] DEBUG nextflow.Session - Session await > all process finished
Sep-29 12:02:13.747 [main] DEBUG nextflow.Session - Session await > all barriers passed
Sep-29 12:02:13.776 [main] INFO  nextflow.script.BaseScript - Pipeline BIOCORE@CRG Master of Pore - preprocess completed!
Sep-29 12:02:13.778 [main] INFO  nextflow.script.BaseScript - Started at  2022-09-29T12:02:04.079266-06:00
Sep-29 12:02:13.779 [main] INFO  nextflow.script.BaseScript - Finished at 2022-09-29T12:02:13.770857-06:00
Sep-29 12:02:13.781 [main] INFO  nextflow.script.BaseScript - Time elapsed: 9.7s
Sep-29 12:02:13.781 [main] INFO  nextflow.script.BaseScript - Execution status: failed
Sep-29 12:02:13.785 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=1; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=1; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=1.1s; failedDuration=2.5s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=2; peakCpus=2; peakMemory=16 GB; ]
Sep-29 12:02:13.936 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Sep-29 12:02:13.961 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by jayradke** [comment]
We have been working up to multiple reads. We can do a single FAST5 just fine. But if we try more than one FAST5 we get this error. We also get this error if we have a single FAST5 in the file indicate even though if we just use the FAST5 file alone pre-process completes.

**Comment by jayradke** [comment]
here is an update...if i run with this command 
./nextflow run mop_preprocess.nf -with-docker -w //mnt/h/Work --fast5 //mnt/h/fast5_pass/*.fast5 --reference Genome.fa --output //mnt/h/Output --annotation Annotation.gtf

it works but it only uses one of the fast5 files in that folder. the files are all from the same sample so i wouldnt think demultiplexing needs to be on.

**Comment by lucacozzuto** [comment]
Mmm, try with granularity 1. Here I read that:

```
Found 0 input read files to process.
Init time: 873 ms
```

And for the command line you should use the "
so is

./nextflow run mop_preprocess.nf -with-docker -w //mnt/h/Work --fast5 "//mnt/h/*/*.fast5" --reference Genome.fa --output //mnt/h/Output --annotation Annotation.gtf

Luca

**Comment by jayradke** [comment]
Adding " in the command line did not work. 

Adding the path to the Fast5 files in the params.config, then removing the -- fast5 from the command line seems to have worked. Currently on file 20 of 245.

I also decreased the granularity to 1. I will update when the preprocess is completed.

**Comment by jayradke** [comment]
completed...now to figure out how to get counting and discovery to work
