### ISSUE TITLE
Bug identifying files

### ISSUE THREAD

**Issue by ky66** [biocorecrg/MOP2#3]
I think there is bug where the software cannot identify the fast5 or fastq files it is given. When I run MOP2, I get:

Argument of `file` function cannot be empty

 -- Check script '../BioNextflow/subworkflows/read_count/htseq.nf' at line: 65 or see '.nextflow.log' file for more details
Cannot find any file matching: /path/*.fastq
 If I do "ls /path/*.fastq" it will identify the files but the pipeliner can't and gives the error above.

I appreciate your help

**Comment by ky66** [comment]
Sending the email to yazdanik2@nih.gov

----------------------CHECK TOOLS -----------------------------
> basecalling will be skipped
> demultiplexing will be skipped
mapping : minimap2
filtering : nanoq
counting : htseq
> discovery will be skipped
--------------------------------------------------------------
Argument of `file` function cannot be empty

 -- Check script '../BioNextflow/subworkflows/read_count/htseq.nf' at line: 65 or see '.nextflow.log' file for more details
Cannot find any file matching: /data/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/guppy_out/pass/all_guppy.fastq

 -- Check script 'mop_preprocess.nf' at line: 575 or see '.nextflow.log' file for more details

**Comment by lucacozzuto** [comment]
Can you add the part of the params?

**Comment by lucacozzuto** [comment]
Ah, it looks like you are trying to count without annotations! HTSEQ needs a GTF file for read counts. Maybe I should trigger an error in that case (even is clearly written No such variable: annotation)...

**Comment by ky66** [comment]
I will try adding the annotation but the error that is raised is due to the pipeline not finding the FAST5 files in the first step.

**Comment by lucacozzuto** [comment]
Keep me posted.

**Comment by ky66** [comment]
Getting this error now after adding the gtf file. 


----------------------CHECK TOOLS -----------------------------
basecalling : guppy
> demultiplexing will be skipped
mapping : minimap2
filtering : nanoq
counting : htseq
> discovery will be skipped
--------------------------------------------------------------
Pulling Singularity image docker://biocorecrg/mopbasecall:0.2 [cache /vf/users/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/MOP2/mop_preprocess/../singularity/biocorecrg-mopbasecall-0.2.img]
Pulling Singularity image docker://biocorecrg/mopprepr:0.7 [cache /vf/users/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/MOP2/mop_preprocess/../singularity/biocorecrg-mopprepr-0.7.img]
Error executing process > 'flow1:GUPPY_BASECALL:baseCall (fast5_pass---21)'

Caused by:
  Cannot run program "qsub" (in directory "/data/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/temp/66/618ad5bd052f3c8b2d2bf40ebba6e0"): error=2, No such file or directory

Command executed:

  qsub -terse .command.run

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /data/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/temp/66/618ad5bd052f3c8b2d2bf40ebba6e0

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


Pipeline BIOCORE@CRG Master of Pore - preprocess completed!
Started at  2022-02-02T10:47:14.372636512-05:00
Finished at 2022-02-02T10:47:41.697920065-05:00
Time elapsed: 27.3s
Execution status: failed
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_preprocess.nf' at line: 631 or see '.nextflow.log' file for more details

**Comment by lucacozzuto** [comment]
Which scheduler are you using?

**Comment by ky66** [comment]
I am using linux on a cluster using SLURM to submit jobs mostly. I don't know what you mean by scheduler otherwise.

**Comment by lucacozzuto** [comment]
Aha, so we need to use another configuration file (they are in conf/ folder). In Nextflow you need to indicate which scheduler you are using (SGE, Slurm etc)

**Comment by lucacozzuto** [comment]
I added a new config file, please do a git pull.
Now it should work if you do:
nextflow run mop_preprocess.nf  -profile slurm

**Comment by ky66** [comment]
Did exactly that ... now the new log file just says:

N E X T F L O W  ~  version 21.10.5
Launching `mop_preprocess.nf` [big_stone] - revision: ecf5447b25

and then this does not change. It is been like this for a while.

**Comment by lucacozzuto** [comment]
Of course you need to add also:  
```
-with-singularity -bg -w /data/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/temp 
```
then you should have a number of submissions

**Comment by ky66** [comment]
Now, it says in the command line right after nextflow: "$ Unknown configuration profile: 'slurm'"
my nextflow script is this:

nextflow run mop_preprocess.nf -with-singularity -bg -w /data/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/temp -profile slurm > log.txt

**Comment by lucacozzuto** [comment]
Well maybe the pull did not work. Can you check that your nextflow.global.config is like that? 
https://github.com/biocorecrg/MOP2/blob/main/nextflow.global.config

**Comment by ky66** [comment]
Changed the new nextflow.global.config file. Now I get this error:

Pulling Singularity image docker://biocorecrg/mopprepr:0.7 [cache /vf/users/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/MOP2/mop_preprocess/../singularity/biocorecrg-mopprepr-0.7.img]
Error executing process > 'flow1:GUPPY_BASECALL:baseCall (fast5_pass---11)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: invalid option -- 'l'
  Try "sbatch --help" for more information

Work dir:
  /data/Schneekloth_Group/Kamyar_data/Kamyar_RNA_Seq/Nanopore_PreQ1/Unmodified/fast5_pass/masterofpores/temp/fa/21b6aad5e75add0118077f14f46052

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`


Pipeline BIOCORE@CRG Master of Pore - preprocess completed!
Started at  2022-02-02T11:33:49.873060407-05:00
Finished at 2022-02-02T11:34:02.432909882-05:00
Time elapsed: 12.6s
Execution status: failed
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_preprocess.nf' at line: 631 or see '.nextflow.log' file for more details

**Comment by lucacozzuto** [comment]
Sorry there was some left over from SGE configuration. Try to do a git pull or to replace the conf/slurm.config
