### ISSUE TITLE
no output for Nanoconsensus

### ISSUE THREAD

**Issue by jason2389** [biocorecrg/MOP2#42]
Hi Luca, 
first of all thanks for this great resource! It makes my life much easier. I have run the pipeline with the test data and when I reach the mop_consensus module, it does not produce any output folder, although it say that the process is completed. Please see below:

N E X T F L O W  ~  version 22.10.6
Launching `mop_consensus.nf` [elegant_lichterman] DSL2 - revision: d4ddf1d0a4

╔╦╗╔═╗╔═╗  ╔═╗╔═╗╔╗╔╔═╗╔═╗╔╗╔╔═╗╦ ╦╔═╗
║║║║ ║╠═╝  ║  ║ ║║║║╚═╗║╣ ║║║╚═╗║ ║╚═╗
╩ ╩╚═╝╩    ╚═╝╚═╝╝╚╝╚═╝╚═╝╝╚╝╚═╝╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG Master of Pores 2. Get consensus modifications - N F  ~  version 2.0
====================================================

*****************   Input     *********************
input_path               : /home/jason_s/bioinf_isilon/Research/TOMAZOU/Internal/jason/Nanopore/MOP2/mop_consensus/../mop_mod/output_mod
output                   : /home/jason_s/bioinf_isilon/Research/TOMAZOU/Internal/jason/Nanopore/MOP2/mop_consensus/output
comparison               : /home/jason_s/bioinf_isilon/Research/TOMAZOU/Internal/jason/Nanopore/MOP2/mop_consensus/comparison.tsv
padsize                  : 50

******* reference has to be the genome **********
reference                : /home/jason_s/bioinf_isilon/Research/TOMAZOU/Internal/jason/Nanopore/MOP2/mop_consensus/../anno/yeast_rRNA_ref.fa.gz
email                    : yourname@yourdomain

Sending the email to yourname@yourdomain

[-        ] process > checkRef   -
[-        ] process > indexFasta -

executor >  local (1)
[7a/77d56d] process > checkRef (Checking yeast_rRNA_ref.fa.gz) [  0%] 0 of 1
[-        ] process > indexFasta                               -
[-        ] process > nanoConsensus                            -

executor >  local (1)
[7a/77d56d] process > checkRef (Checking yeast_rRNA_ref.fa.gz) [  0%] 0 of 1
[-        ] process > indexFasta                               -
[-        ] process > nanoConsensus                            -

executor >  local (1)
[7a/77d56d] process > checkRef (Checking yeast_rRNA_ref.fa.gz) [100%] 1 of 1 ✔
[-        ] process > indexFasta                               [  0%] 0 of 1
[-        ] process > nanoConsensus                            -

executor >  local (2)
[7a/77d56d] process > checkRef (Checking yeast_rRNA_ref.fa.gz) [100%] 1 of 1 ✔
[53/c6fc4c] process > indexFasta (reference.fa)                [  0%] 0 of 1
[-        ] process > nanoConsensus                            -

executor >  local (2)
[7a/77d56d] process > checkRef (Checking yeast_rRNA_ref.fa.gz) [100%] 1 of 1 ✔
[53/c6fc4c] process > indexFasta (reference.fa)                [100%] 1 of 1 ✔
[-        ] process > nanoConsensus                            -
Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2023-04-04T15:17:29.342723+02:00
Finished at 2023-04-04T15:17:35.874643+02:00
Time elapsed: 6.5s
Execution status: OK
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_consensus.nf' at line: 158 or see '.nextflow.log' file for more details

executor >  local (2)
[7a/77d56d] process > checkRef (Checking yeast_rRNA_ref.fa.gz) [100%] 1 of 1 ✔
[53/c6fc4c] process > indexFasta (reference.fa)                [100%] 1 of 1 ✔
[-        ] process > nanoConsensus                            -
Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2023-04-04T15:17:29.342723+02:00
Finished at 2023-04-04T15:17:35.874643+02:00
Time elapsed: 6.5s
Execution status: OK
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'mop_consensus.nf' at line: 158 or see '.nextflow.log' file for more details

**Comment by lucacozzuto** [comment]
@ADelgadoT

**Comment by lucacozzuto** [comment]
Can you pass the log? And the log of mop_mod?

**Comment by ADelgadoT** [comment]
Also, could you send us the contents of the comparison.tsv files from mop_mod and mop_consensus directories? Thanks!

**Comment by jason2389** [comment]
In the meantime I have solved the problem. The issue was with the conda enviroment I was using and the version of Nextflow. Thanks!

**Comment by nawa2179** [comment]
> In the meantime I have solved the problem. The issue was with the conda enviroment I was using and the version of Nextflow. Thanks!

Hi Jason, 

Can you tell me the nexflow version that you use for solve this issues ? 

Thanks !
