### ISSUE TITLE
Error when running mop_mod

### ISSUE THREAD

**Issue by AndreaYCT** [biocorecrg/MOP2#46]
Hi, 

I have been trying these few weeks (at different time) and still get the same error.

```
Error executing process > 'compore_polish_flow:NANOPOLISH_EVENTALIGN:index (wt)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name biocorecrg-mopnanopolish-0.2.img.pulling.1683256214123 docker://biocorecrg/mopnanopolish:0.2 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://biocorecrg/mopnanopolish:0.2: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp 52.1.184.176:443: i/o timeout
```

Is there anything I did wrong?
[MOP2_mod_log_202305051110.txt](https://github.com/biocorecrg/MOP2/files/11403033/MOP2_mod_log_202305051110.txt)

**Comment by lucacozzuto** [comment]
Hi, this is either a problem with downloading the image from docker hub or your ~/.singularity folder is full.

**Comment by AndreaYCT** [comment]
Hi, 

I was running this on HPC. To use Singularity,  i loaded the module as below:
```
module load biology/nextflow/22.04.0
module load libs/singularity/3.10.2

cd /staging/biology/USER/MOP2/mop_mod

# run
nextflow run mop_mod.nf -with-singularity 
```

Is it possible caused by unwritable of singularity folder?

Thank you!

**Comment by AndreaYCT** [comment]
I manually pull the image by 
"singularity pull --name biocorecrg-mopnanopolish-0.2.img.pulling.1683508359263 docker://biocorecrg/mopnanopolish:0.2"

Then it worked :)
