### ISSUE TITLE
Error with Graphmap/samtools

### ISSUE THREAD

**Issue by matjack2000** [biocorecrg/MOP2#48]
Hello,
![Capture d’écran du 2023-07-10 09-19-39](https://github.com/biocorecrg/MOP2/assets/130562895/149e8644-6fc6-45a6-9a31-cc33fc000606)
I get an error when I try to use mop_preprocess on my data (which are on fast5, so it's not supposed to be an issue). My reference is the human transcript ( https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_43/gencode.v43.transcripts.fa.gz ). 
I also ran it with docker and tried to switch to minimap2.
Thanks in advance for your answer.
[log.zip](https://github.com/biocorecrg/MOP2/files/11999038/log.zip)

**Comment by lucacozzuto** [comment]
So you are using graphmap with one CPU for aligning to the whole transcriptome... I see that after a while it just exit. Likely a problem of RAM. Try to switch to minimap2
