### ISSUE TITLE
Using pre-trained models for modification prediction (MOP_mod)

### ISSUE THREAD

**Issue by rugilemat** [biocorecrg/MOP2#51]
Hi all,

I was looking into the MOP_MOD workflows and from what I understand they are implementing Epinano, Nanopolish, Tombo and Nanocompore in KD/KO vs WT modes.

I know Epinano and tombo can use pre-trained models without the KO/KD condition (e.g. Epinano-SMV), I was wondering if there's a way to use that through MOP2 or if you have any plans to implement this in the future?

**Comment by lucacozzuto** [comment]
@ADelgadoT @enovoa

**Comment by enovoa** [comment]
Hi @rugilemat the implementation of Epinano in MoP2 corresponds to Epinano-Error, not Epinano-SVM. Pre-trained models can be used with Epinano-SVM if you use standalone Epinano, but not as part or MoP2. Thanks!

**Comment by rugilemat** [comment]
Hi @enovoa thanks! Do you have any plans to implement Epinano-SVM into MOP2 in the future?

**Comment by enovoa** [comment]
Not in the plans at the moment, sorry

**Comment by rugilemat** [comment]
I see, thanks!
