### ISSUE TITLE
Unable to execute guppy on a seemingly random fast5 file. 

### ISSUE THREAD

**Issue by joesimop** [biocorecrg/MOP2#57]
Right now I am running MOP2 with singularity version 3.8.0 and guppy version 6.5.7. On a Linux x86_64 machine.

I am getting a similar error mentioned in [this issue](https://github.com/biocorecrg/MOP2/issues/8).
It is worth noting that this is happening on the 61st file a directory of 65 files, without any of the other files errorring out.

Here is the command executed followed by the .nextflow.log output:

`  guppy_basecaller          --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002 --disable_qscore_filtering -i ./         --save_path ./botrylloides_fast5_FAK64140---61_out         --gpu_runners_per_device 1         --cpu_threads_per_caller 1 	    --num_callers  8
  cat botrylloides_fast5_FAK64140---61_out/*.fastq >> botrylloides_fast5_FAK64140---61.fastq
  rm botrylloides_fast5_FAK64140---61_out/*.fastq
  gzip botrylloides_fast5_FAK64140---61.fastq
`

`Command error:
  Unexpected option '--disable_qscore_filtering' found on command line.
  
  ONT Guppy basecalling software version 4.0.15+5694074, client-server API version 2.1.0
  config file:        /mnt/keeling/installations/MOP2/mop_preprocess/bin/ont-guppy/data/rna_r9.4.1_70bps_hac.cfg
  model file:         /mnt/keeling/installations/MOP2/mop_preprocess/bin/ont-guppy/data/template_rna_r9.4.1_70bps_hac.jsn
  input path:         ./
  save path:          ./botrylloides_fast5_FAK64140---61_out
  chunk size:         2000
  chunks per runner:  512
  records per file:   4000
  num basecallers:    8
  cpu mode:           ON
  threads per caller: 1
  
  Found 1 fast5 files to process.
  Init time: 10027 ms
  
  Caller time: 302 ms, Samples called: 0, samples/s: 0
  There were fast5 file loading problems! Failed to load 1 out of 1 fast5 files. Check log file for details.
  Finishing up any open output files.
  Basecalling completed successfully.
  cat: 'botrylloides_fast5_FAK64140---61_out/*.fastq': No such file or directory
`
If you look at the aforementioned Github issue, the errors are similar. The output errors are only different because I attempted to put "--diable_qscore_filtering" inside the params.config file for guppy basecalling, as suggested by the post. I checked the flags for the guppy_basecaller commands and it is a valid flag, but it is possible it is being put in the wrong place for command-line arguments. 

If anyone has anyway of fixing this or have come across it in the past, please let me know. It has been a thorn in my side for about a week! I'll be quick to respond if more information is needed.

**Comment by lucacozzuto** [comment]
Hi, that version is not supported. They changed too much the command line. I will give support soon in the next version of MoP (MoP3) that will be out soon
