### ISSUE TITLE
nanopolish not executing

### ISSUE THREAD

**Issue by tzcoolman** [biocorecrg/MOP2#58]
Hi Luca,

Thanks for the pipeline. 
I was running mop_tail and encountered the issue people previously reported:
https://github.com/biocorecrg/MOP2/issues/20
I was able to get away with it by doing 'nextflow -self-update'
The program was able to download nanopolish, however, this is what I got from the log file:

executor >  local (12)
[-        ] process > TAILFINDR_ESTIMATE_TAIL:est... -
[-        ] process > collect_tailfindr_results      -
[15/f6ce7b] process > checkRef (Checking GRCh38.p... [100%] 1 of 1 ✔
[db/430059] process > filter_bam (SGNex_Myeloma-N... [100%] 4 of 4 ✔
[19/ed9f58] process > SAMTOOLS_INDEX:indexBam (SG... [100%] 4 of 4 ✔
[-        ] process > NANOPOLISH_POLYA_LEN:polyAtail -
[-        ] process > NANOPOLISH_POLYA_LEN:collec... -
[-        ] process > join_nanotail_results          -
[c1/8a13a1] process > TAILFINDR_VER:getVersion       [100%] 1 of 1 ✔
[0b/108860] process > NANOPOLISH_VER:getVersion      [100%] 1 of 1 ✔
[f8/9a5349] process > SAMTOOLS_VER:getVersion        [100%] 1 of 1 ✔
Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2024-02-26T14:10:21.925352849-05:00
Finished at 2024-02-26T14:16:11.289517940-05:00
Time elapsed: 5m 49s
Execution status: OK
Completed at: 26-Feb-2024 14:16:11
Duration    : 5m 49s
CPU hours   : 0.7
Succeeded   : 12

The nanopolish img was there. Iooks like it was not executed. Is there anyway to fix it? Thx.

tzcoolman

**Comment by lucacozzuto** [comment]
can you send me the log, please?

**Comment by tzcoolman** [comment]
[log.txt](https://github.com/biocorecrg/MOP2/files/14437843/log.txt)

Hi Luca,

Here it is.

**Comment by lucacozzuto** [comment]
Hi, so I used the test data and it worked. Can you check you got all the outputs from mop_preprocess?

**Comment by lucacozzuto** [comment]
In particular you need the following outputs:
```
/alignment/*_s.bam
/alignment/*_s.bam.bai
/fastq_files/*.fq.gz
/fast5_files/*
/assigned/*.assigned
```

**Comment by tzcoolman** [comment]
![capture2](https://github.com/biocorecrg/MOP2/assets/1256961/debba377-ee03-4f40-8a06-a04529f7c42f)
I double-checked those files and they were there.
Is there any verbose mode that I can use to see more tail of the processing results?

**Comment by lucacozzuto** [comment]
you can checkk the .nextflow.log in which more info are stored. I'm actually surprised. Can you also check the toy dataset?

**Comment by tzcoolman** [comment]
Yes. The pipeline works with toy dataset. I directly used fastq files as input for mop_preprocess thus got error in mop_tail steps. Thank you Luca.
