### ISSUE TITLE
RE: running mop_preprocessing on multiple runs

### ISSUE THREAD

**Issue by Malabady** [biocorecrg/MOP2#9]
Hi, 
I have three minion runs of dRNA that I am trying to analyze using MOP2. 

- I understand that it is possible to run mop_prerocessing on multiple runs. I am not clear on how to input the kit and flow cell info though. in the docs, it says they can be inputed in one of the _opt.tsv file. I used the following:
Library prep kit: SQK-RNA002
Flowcell: FLO-MIN106
Is this all info that I need to add to one of the _opt.tsv files? I yes, what formate? 

alternatively, I have the "final_summary.txt" for the three runs. can I cat them in one file and pass it to the `confine` option?

- I had base calling done during the sequencing run. So, I have both fast5_fail and fast5_pass. I understand the the this mop_preporcessing with do the base calling. so, can I just combine both passed and failed fast5 in one file per run and pass them to the workflow? 

- there are three dRNA *_opt.tsv files. 
```
drna_tool_splice_opt.tsv
drna_tool_unsplice_guppy6_opt.tsv
drna_tool_unsplice_opt.tsv
```
I am clear on when to use the splice or unsplice parameters. what exactly is the difference? also, can the flag ``--disable_qscore_filtering`` be passed to guppy in the splice parameter file? 

Many thanks,

**Comment by lucacozzuto** [comment]
Hi, you can analyze multiple runs if the library prep kit and flowcell are the same. You just need to pass one final_summary.txt 
If not you have to run the runs separately. If you don't need the basecalling you can skip that part and pass just the fastq files (concatenated fail and pass) but then you cannot run the other pipelines. Splice and unsplice depends on the kind of mapping you want (to the genome or transcriptome). The file *guppy6_opt.tsv is for newer guppy versions where you have to specify the option for skipping the separation between fail and pass.

**Comment by Malabady** [comment]
Many thanks for quick reply. Really appreciated. 
I need to run all other pipelines, so I must start from the bas calling step. Can I `cat` the passed and failed fast5 from the three runs in one file and pass it mop_preprocessing? 

As for the final_summary.txt: so if I pass only one file since I used the same kit and same flow cell type, some info like flow_cell_id will be lost. Is it not needed? 

I am mapping to Transcriptome, so I'll use the unsplice option. When I installed MOP2, I used the Install.sh, which installs guppy 3.4.5. So, in this case I should use `drna_tool_unsplice_opt.tsv`. Correct? 

Finally, about disabling the qscore filtering to avoid losing interesting signals, as mentioned in the following note:
``You can pass via parameter a custom NAME_tool_opt.tsv file with custom guppy options to disable the qscore filtering. Some custom files are already available in this package, like drna_tool_unsplice_guppy6_opt.tsv``

in drna_tool_unsplice_opt.tsv file, can I do this:
`filtering       nanoq   "No"`

Also, In the parameter.config  file, there is the following line:
 `filtering           = "nanoq"`

Do I need to change it to 
` filtering           = "No"`

**Comment by lucacozzuto** [comment]
1) I recommend you to basecall again your files
2) you can use a newer version of guppy by installing bash Install.sh and the version you have (but you need to remove the guppy files that are there or reinstall mop2 in another folder) and using the opt.tsv for guppy6
3) in opt tsv you just introduce the command line you want. So if you don't need nanoq you just can put "" in opt.tsv and in params.config you put filtering = NO
